language: node_js
services:
- docker
script:
- npm test
- docker build -t webscreenshot .
deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  api_key:
    secure: Dms5FIx58iWwOnH6YgMLTOAcpv+U0WqPVqd70f0xxJNedyE5+2tLcBtm7tFZIdGYC2Au8D8ZVC2BmIqonio/17l90ukmhhRK7CGvEfzYbQexVLvwmhnkGuBAHmCf/PrdGRNFLjSq6ule043xkDZ2Nr9k/QriRR5EaU2SPh4xBweS2Umzunr3SYv74DyAG/+fbXh0rTP76CK05CAiQc/12o5EnbeX2W+TMuUg8aQEXH80s4yaxSNcn5rW38MmbQQs46oBoqvqV22Ey8Fu1ogMrGhqdLLn/fOIW1zvjemAmUPBD1Ui1glVIelk57aPcR3hB8rB493NIIgQDS6SfczhNt53AhKVnHwsKgX7nRcSVAG9jg7Fzs6a9n0cjuRumXiZhBlmcpzW4UKi9kIn00nb+6NIPzTewsUVeU8YsuryXALwLSadKxoKRyAfmV1zLZbY4ClxZsMlKy5swGKHT68Eatg/mUO06nE/w6GQLmfRx9eV/i8gcfJfjirl3e0uvF3v8GAF+bfTr5PZ6O3ciLTemB7HhTX0i6Bui7u4Vj69d8oA2/wmAe1Byk16MP/+t589Oj119qRYBCym1tVk5DFiMUkXUstQyV8VXwHkEmCrcm2F3U9VJF4smP/Kg+JDCa5KNBcpOheMMJRZmX7/09zGLW55fT7dUv84s+UaA1izEf4=
  on:
    tags: true
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
