language: node_js
services:
- docker
script:
- npm test
- docker build -t webscreenshot .
deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  api_key:
    secure: mB/Cgp1ZwZ8DDpgtJk7r4EvA4ndI2Cc3B7tX6FF/kPo94D6dP4iIFuW9l/ZrYUJlcP7zFEbUDsf7b64W8TgtJIqECAeaHW4jwKUP8i5xSLaiOxLnMKTYsPzX8Mu/3cyUWDYcWAWTfjvYGhIaiuoWG+r6FVHdyeYSufMOOsyQhsCJJhbgj0U9uOwXpU4ZiKGCPHL3tuvg81T7jkj+gZFc3u5o7Jbgq77k5CLxa4dUE8Omboss/MibR8Y537OsVZTnOUWaAGdV0pC1O+AsekCbwa9bDXhFVGJ5paQabbOiFcLeQsflDTs6sHPedcFRBBNWg/MHak78gNwwBlWNiRlcnvrtUehRHk6EgEnM6jxVBgIQA50p9Mih/zwBBBRL4P4+jL8e41h0Mq76nBnb0HoAmEvB2kbGjBzyR5aj68s34DH52nIVWyhpa3ZSlbMyFw6HpR2vGhMHjyo3OGvqLDfjEI0OHjZAdLUOTBgzINWHqVCzV93df0dpdF0EM6pUJtwAoeN3Tbaw3+6cGZArUoRHVKMeBVOrYwGKvytgeUaD5kQwbAvH1WIA+Hc7wWmbhmQ8ElnD3JiD0dsOIPaH6004wJuI+M3yNFmocjwO6WZGstFPGWPJ7X+S04NQYZcVsqes3IvtDc0z+pXP8weDa/wC2etHh4kZ5yWZn/BKtrrV8AE=
  on:
    tags: true
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
